force-app/main/default/objects/User__c/User__c.object-meta.xml
<CustomObject>
    <label>User</label>
    <nameField>
        <displayFormat>U-{000}</displayFormat>
        <label>User ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Huntsville</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Montgomery</fullName>
            </value>
            <value>
                <fullName>Anchorage</fullName>
            </value>
            <value>
                <fullName>Juneau</fullName>
            </value>
            <value>
                <fullName>Fairbanks</fullName>
            </value>
            <value>
                <fullName>North Pole</fullName>
            </value>
            <value>
                <fullName>Phoenix</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>Scottsdale</fullName>
            </value>
            <value>
                <fullName>Mesa</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Nashik</fullName>
            </value>
            <value>
                <fullName>Mehrauli</fullName>
            </value>
            <value>
                <fullName>Siri</fullName>
            </value>
            <value>
                <fullName>Tughlakabad</fullName>
            </value>
            <value>
                <fullName>Firozabad</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Tiruchirapalli</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>TamilNadu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountControllerLWC.cls
public with sharing class AccountControllerLWC {
    // @AuraEnabled(cacheable=true)
    // public static List<Contact> queryRelatedContacts(Id accountId) {
    //     return [ select Name, Title, Email, Phone,Account.Name from Contact where AccountId = :accountId];

    // }
        @AuraEnabled(cacheable=true)
        public static List<User__c> queryRelatedUser(Id Name) {
            return [ select Name, First_Name__c, City__c, State__c, Phone__c, Email_Address__c from User__c];
    
        }


        @AuraEnabled
        public static string deleteSelectedAccounts(List<ID> accIDList){
            try {
                if(!accIDList.isEmpty()){
                delete ([select Name from User__c where Id IN : accIDList]);
                return 'Selected Records have been deleted successfully...!!!';
                }
                else{
                        return 'There is no records are selected';
                }
            } catch (Exception e) {
    
                 System.debug('# Messege = '+e.getMessage());
                 return 'SomeProblem..!!';
    
               
               
            }
        }



        @AuraEnabled
    public static List<User__c> getAllAccountsType(Id Name){
        try {
          
            return ([select Name, First_Name__c, City__c, State__c, Phone__c, Email_Address__c from User__c]);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }



    //======================Delete Selected Users to Admin in Lightning web component===========================
    
@AuraEnabled
public static List<User__c> fetchUsers(){
    return [SELECT Id, Name, First_Name__c, City__c, State__c, Phone__c, Email_Address__c from User__c LIMIT 9];
}

//create a account classcode
@AuraEnabled
    public static String createUserRecord(User__c objUser){
        try {
            insert objUser;
            return 'Record created successfully...!!!';

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }




        
}